services:
    newscoop_twwidgets_plugin.lifecyclesubscriber:
        class: Newscoop\TagesWocheWidgetsPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}
